select*from customer limit 10

--Q1. befor use the colums check their properties

USE customer_behavior;
SELECT 
	SUM(monthly_charges) AS total_monthly_charges,
    AVG(monthly_charges) AS average_monthly_charges,
    COUNT(*) AS total_rows,
    COUNT(monthly_charges) AS non_null_monthly_charges
FROM customer;

--Q2. What is the total revenue generated by male vs. female customers?

select gender , sum(total_charges) as revenue
from customer
group by gender

--Q3. Which subscription type reach the  highest average review rating?

select subscription_type , avg(satisfaction_score) as "average subscription_type rating"
from customer 
group by subscription_type
order by avg(satisfaction_score) desc


--Q4. Compare the average Purchase Amounts between basic and premium subscription_type.

select subscription_type , avg(monthly_charges) , avg(total_charges)
from customer
group by subscription_type
order by  avg(monthly_charges) , avg(total_charges)  desc

--Q5. Do subscribed customers premium customer use more or basic customer use more or standard customer use more the subscription?

SELECT subscription_type, usage_frequency
FROM (
    SELECT subscription_type,
           usage_frequency,
           COUNT(*) AS cnt,
           RANK() OVER (PARTITION BY subscription_type 
                        ORDER BY COUNT(*) DESC) AS rnk
    FROM customer
    GROUP BY subscription_type, usage_frequency
) t
WHERE rnk = 1;
   
--Q6. What is the revenue contribution of each age group?

select age_group , sum(total_charges)
from customer
group by age_group 
order by sum(total_charges) desc 